// Sponsorlar ve iletişim bilgileri buradan yönetilir. Boş bilgiler canlı görünümde gösterilmez.
export const siteConfig = {
  contactEmail: 'partechyperloop@gmail.com',
  instagramUrl: 'https://www.instagram.com/partechyperloop/',
  partnershipDeck: '',
  // Liste sırası ekrandaki sıradır. featured logolar üst sırada gösterilir.
  partners: [
    {name:'KARDEMİR', logo:'assets/sponsors/kardemir.png', featured:true},
    {name:'Karabük Üniversitesi', logo:'assets/sponsors/karabuk-universitesi.png', featured:true},
    {name:'Yılmaz Redüktör', logo:'assets/sponsors/yilmaz-reduktor.png', padded:true},
    {name:'SOMAL', logo:'assets/sponsors/somal.png'},
    {name:'The Lean Six Sigma Company', logo:'assets/sponsors/lean-six-sigma.png'},
    {name:'İ-Mak', logo:'assets/sponsors/i-mak.jpeg', padded:true},
    {name:'Millî Teknoloji Atölyeleri', logo:'assets/sponsors/milli-teknoloji-atolyeleri.webp'}
  ],
};
export const copy = {
 en: {
  home:'Home',about:'About',technology:'Technology',achievements:'Achievements',partners:'Partners',news:'News',contact:'Contact',
  heroLabel:'PARTECH HYPERLOOP · PROTOTYPE DEVELOPMENT',heroTitle:'Engineering the Future of Mobility.',heroText:'We are PARTECH, a Turkish Hyperloop engineering team bringing ideas to life through design, hands-on development and collaboration.',explore:'Explore Our Pod',partner:'Partner With Us',focus:'Our focus',approach:'Our approach',prototype:'Design & Prototype',strength:'Our strength',teamwork:'Engineering Together',discover:'Discover our engineering',
  techLabel:'PARTECH TECHNOLOGY',techTitle:'From Engineering Ideas to a Working Prototype.',techIntro:'Explore the prototype and the engineering disciplines behind our work on the next generation of transportation.',podCaption:'Our prototype, presented at TEKNOFEST.',ourApproach:'Discover Our Approach',
  aboutLabel:'ABOUT THE INITIATIVE',aboutTitle:'Engineering Together. Looking Further.',aboutText:'PARTECH brings together a team working on Hyperloop technology. Our journey connects engineering ideas with the practical experience of developing a physical prototype.',aboutText2:'We aim to strengthen our work through knowledge sharing, industry support and future international collaborations. Each new stage is an opportunity to learn, improve and build together.',principle1:'Hands-on Engineering',principle1Text:'Learning through prototype development and collaboration.',principle2:'Shared Ambition',principle2Text:'Connecting our team with industry and research communities.',teamCaption:'PARTECH team at the Hyperloop competition.',teamNote:'The people behind the prototype.',
  achievementsLabel:'OUR TRACK RECORD',achievementsTitle:'Every Season. A Step Forward.',achievementsText:'From our first finals in 2023 to awards for engineering development and performance: explore the milestones in our TEKNOFEST journey.',
  partnersLabel:'SPONSORS & PARTNERS',partnersTitle:'Progress Built Together.',partnersText:'Engineering grows through collaboration. We welcome organizations ready to support our next chapter.',becomePartner:'Become a Partner',
  teamLabel:'THE MINDS BEHIND PARTECH',teamTitle:'One Team. Many Disciplines. A Shared Direction.',teamText:'Our prototype brings together the curiosity, effort and different perspectives of the people behind PARTECH.',join:'Connect With Our Team',
  newsLabel:'FROM THE FIELD',newsTitle:'Inside PARTECH.',
  contactLabel:'LET’S CONNECT',contactTitle:'Let’s Build the Next Chapter.',contactText:'We welcome conversations with industry partners, researchers and future teammates.',contactPending:'Our partnership contact details will be shared here soon.',contactPrompt:'For partnership, research and team inquiries:',followUs:'Stay connected',followText:'Follow our team’s journey on Instagram.',emailUs:'Write Us a Message',downloadDeck:'Download Partnership Deck',readMore:'Read More',
  story:'Our Story',team:'Team',opportunities:'Partnership Opportunities',updates:'Updates',media:'From the Field',
  disciplines:[['Mechanical Systems','Developing the prototype’s structural components and mechanical assemblies.'],['Electronic Systems','Developing the electronic circuits, sensors and communication infrastructure that support the prototype.'],['Electromechanical Systems','Combining electrical and mechanical engineering to design and manufacture linear induction motors.'],['Software & Control Systems','Developing software and control algorithms to monitor and manage the prototype’s systems.']],
  articles:[['assets/event.jpg','EVENT','Sharing Our Engineering','A closer look at our prototype and the conversations around it.','Events give our team a chance to explain our work, share ideas and bring engineering closer to visitors. These photographs document PARTECH’s presence at TEKNOFEST.'],['assets/pod.jpg','PROTOTYPE','A Closer Look at Our Pod','Explore the prototype displayed alongside its exposed hardware.','The display brings our pod shell and hardware into view. It offers a closer look at the physical prototype developed by our team. Detailed technical specifications will be added once confirmed.'],['assets/awards.jpg','TEAM','Moments From the Competition','A record of the people and experiences behind PARTECH.','Our competition photographs capture an important part of our team’s journey: working together, presenting our prototype and sharing the experience.']],
  paths:[['Industry & Manufacturing','Support the team through materials, components and manufacturing expertise.'],['Technology & Research','Explore opportunities for technical exchange and research collaboration.'],['Team Support','Help create the resources and opportunities for our next stage.']],
  placeholder:'Partner Logo',placeholderTitle:'Partner introduction',placeholderDescription:'Company introduction and contribution will be added here.',placeholderTypes:['Industry','Academia','Manufacturing','Research','Technology','Support'],
 },
 tr: {
  home:'Ana Sayfa',about:'Hakkımızda',technology:'Teknoloji',achievements:'Başarılar',partners:'Ortaklarımız',news:'Haberler',contact:'İletişim',
  heroLabel:'PARTECH HYPERLOOP · PROTOTİP GELİŞTİRME',heroTitle:'Ulaşımın Geleceğini Tasarlıyoruz.',heroText:'Biz PARTECH. Tasarım, uygulamalı geliştirme ve iş birliğiyle fikirlerini hayata geçiren bir Türk Hyperloop mühendislik takımıyız.',explore:'Aracımızı Keşfet',partner:'İş Birliği Yapalım',focus:'Odak noktamız',approach:'Yaklaşımımız',prototype:'Tasarım ve Prototip',strength:'Gücümüz',teamwork:'Birlikte Mühendislik',discover:'Mühendisliğimizi keşfet',
  techLabel:'PARTECH TEKNOLOJİ',techTitle:'Mühendislik Fikirlerinden Gerçek Bir Prototipe.',techIntro:'Yeni nesil ulaşım üzerine çalışmalarımızın arkasındaki prototipi ve mühendislik disiplinlerini keşfedin.',podCaption:'TEKNOFEST’te sergilenen prototipimiz.',ourApproach:'Yaklaşımımızı Keşfet',
  aboutLabel:'BİZ KİMİZ?',aboutTitle:'Birlikte Geliştiriyor, İleriye Bakıyoruz.',aboutText:'PARTECH, Hyperloop teknolojisi üzerine çalışan bir takımı bir araya getiriyor. Yolculuğumuz, mühendislik fikirlerini fiziksel bir prototip geliştirmenin kazandırdığı deneyimle buluşturuyor.',aboutText2:'Bilgi paylaşımı, sanayi desteği ve gelecekteki uluslararası iş birlikleriyle çalışmalarımızı güçlendirmeyi hedefliyoruz. Her yeni aşama; öğrenmek, geliştirmek ve birlikte üretmek için bir fırsat.',principle1:'Uygulamalı Mühendislik',principle1Text:'Prototip geliştirme ve iş birliğiyle öğreniyoruz.',principle2:'Ortak Hedefler',principle2Text:'Takımımızı sanayi ve araştırma topluluklarıyla buluşturuyoruz.',teamCaption:'Hyperloop yarışmasında PARTECH takımı.',teamNote:'Prototipin arkasındaki insanlar.',
  achievementsLabel:'GEÇMİŞ BAŞARILARIMIZ',achievementsTitle:'Her Sezon Bir Adım İleri.',achievementsText:'2023’te başlayan final yolculuğumuzdan teknoloji geliştirme ve performans ödüllerine: TEKNOFEST’teki başarılarımızı keşfedin.',
  partnersLabel:'SPONSORLAR VE ORTAKLAR',partnersTitle:'Birlikte İlerliyoruz.',partnersText:'Mühendislik, iş birliğiyle gelişir. Yolculuğumuzun bir sonraki aşamasına katkıda bulunmak isteyen kurumları aramıza bekliyoruz.',becomePartner:'İş Ortağımız Olun',
  teamLabel:'PARTECH’İN ARKASINDAKİ EKİP',teamTitle:'Tek Takım. Farklı Disiplinler. Ortak Bir Yön.',teamText:'Prototipimiz, PARTECH’in arkasındaki insanların merakını, emeğini ve farklı bakış açılarını bir araya getiriyor.',join:'Takımımızla Tanışın',
  newsLabel:'SAHADAN NOTLAR',newsTitle:'PARTECH’e Yakından Bakın.',
  contactLabel:'İLETİŞİME GEÇELİM',contactTitle:'Bir Sonraki Adımı Birlikte Atalım.',contactText:'Sanayi ortakları, araştırmacılar ve gelecekteki takım arkadaşlarımızla tanışmak istiyoruz.',contactPending:'İş birliği için iletişim bilgilerimizi yakında burada paylaşacağız.',contactPrompt:'İş birliği, araştırma ve takım başvuruları için:',followUs:'Bizi takipte kalın',followText:'Takımımızın yolculuğunu Instagram’da takip edin.',emailUs:'Bize Yazın',downloadDeck:'Sponsorluk Dosyasını İndir',readMore:'Devamını Oku',
  story:'Hikâyemiz',team:'Takım',opportunities:'İş Birliği Fırsatları',updates:'Güncellemeler',media:'Sahadan Notlar',
  disciplines:[['Mekanik Sistemleri','Prototipin yapısal bileşenlerini ve mekanik düzeneklerini geliştiriyoruz.'],['Elektronik Sistemleri','Prototipin çalışmasını destekleyen elektronik devreleri, sensörleri ve haberleşme altyapısını geliştiriyoruz.'],['Elektromekanik Sistemleri','Lineer indüksiyon motoru tasarımı ve üretimi için elektrik ve mekanik mühendisliğini bir araya getiriyoruz.'],['Yazılım ve Kontrol Sistemleri','Prototipin sistemlerini izlemek ve yönetmek için yazılım ve kontrol algoritmaları geliştiriyoruz.']],
  articles:[['assets/event.jpg','ETKİNLİK','Mühendisliğimizi Anlatıyoruz','Prototipimize ve çevresinde gelişen paylaşımlara yakından bakın.','Etkinlikler; çalışmalarımızı anlatmak, fikir alışverişi yapmak ve ziyaretçileri mühendislikle buluşturmak için bir fırsat. Bu fotoğraflar, PARTECH’in TEKNOFEST deneyimini yansıtıyor.'],['assets/pod.jpg','PROTOTİP','Aracımıza Yakından Bakın','Gövdesi ve donanımıyla sergilenen prototipimizi keşfedin.','Sergi alanı, aracımızın gövdesini ve donanımını bir arada görme fırsatı sunuyor. Takımımızın geliştirdiği fiziksel prototipe yakından bakabilirsiniz. Ayrıntılı teknik veriler doğrulandıktan sonra eklenecek.'],['assets/awards.jpg','TAKIM','Yarışmadan Anlar','PARTECH’in arkasındaki insanları ve deneyimleri bir araya getiren kareler.','Yarışma fotoğraflarımız; birlikte çalışmayı, prototipimizi tanıtmayı ve deneyimlerimizi paylaşmayı içeren takım yolculuğumuzun önemli bir bölümünü kayda geçiriyor.']],
  paths:[['Sanayi ve Üretim','Malzeme, bileşen ve üretim uzmanlığıyla takımımıza destek olun.'],['Teknoloji ve Araştırma','Teknik bilgi paylaşımı ve araştırma iş birliği fırsatlarını keşfedin.'],['Takım Desteği','Bir sonraki aşamamız için kaynak ve fırsatların oluşmasına katkı sağlayın.']],
  placeholder:'Partner Logosu',placeholderTitle:'İş ortağı tanıtımı',placeholderDescription:'Firma tanıtımı ve PARTECH’e katkısı buraya eklenecek.',placeholderTypes:['Sanayi','Akademi','Üretim','Araştırma','Teknoloji','Destek'],
 }
};
