// Sponsorlar ve iletişim bilgileri buradan yönetilir. Boş bilgiler canlı görünümde gösterilmez.
export const siteConfig = {
  contactEmail: '',
  partnershipDeck: '',
  // Örnek: { name:'Firma', logo:'assets/firma.svg', url:'https://...', description:{en:'...',tr:'...'}, contribution:{en:'...',tr:'...'} }
  partners: [],
};
export const copy = {
 en: {
  home:'Home',about:'About',technology:'Technology',achievements:'Achievements',partners:'Partners',news:'News',contact:'Contact',
  heroLabel:'PARTECH HYPERLOOP · PROTOTYPE DEVELOPMENT',heroTitle:'Engineering the Future of Mobility.',heroText:'We are PARTECH, a Turkish Hyperloop engineering team bringing ideas to life through design, hands-on development and collaboration.',explore:'Explore Our Pod',partner:'Partner With Us',focus:'Our focus',approach:'Our approach',prototype:'Design & Prototype',strength:'Our strength',teamwork:'Engineering Together',discover:'Discover our engineering',
  techLabel:'PARTECH TECHNOLOGY',techTitle:'From Engineering Ideas to a Working Prototype.',techIntro:'Explore the prototype and the engineering disciplines behind our work on the next generation of transportation.',podCaption:'Our prototype, presented at TEKNOFEST.',ourApproach:'Discover Our Approach',
  aboutLabel:'ABOUT THE INITIATIVE',aboutTitle:'Engineering Together. Looking Further.',aboutText:'PARTECH brings together a team working on Hyperloop technology. Our journey connects engineering ideas with the practical experience of developing a physical prototype.',aboutText2:'We aim to strengthen our work through knowledge sharing, industry support and future international collaborations. Each new stage is an opportunity to learn, improve and build together.',principle1:'Hands-on Engineering',principle1Text:'Learning through prototype development and collaboration.',principle2:'Shared Ambition',principle2Text:'Connecting our team with industry and research communities.',teamCaption:'PARTECH team at the Hyperloop competition.',teamNote:'The people behind the prototype.',
  achievementsLabel:'ENGINEERING MILESTONES',achievementsTitle:'Built Through Experience.',achievementsText:'A look at our team, prototype and competition journey through photographs from the field.',
  partnersLabel:'SPONSORS & PARTNERS',partnersTitle:'Progress Built Together.',partnersText:'Engineering grows through collaboration. We welcome organizations ready to support our next chapter.',becomePartner:'Become a Partner',
  teamLabel:'THE MINDS BEHIND PARTECH',teamTitle:'One Team. Many Disciplines. A Shared Direction.',teamText:'Our prototype brings together the curiosity, effort and different perspectives of the people behind PARTECH.',join:'Connect With Our Team',
  newsLabel:'FROM THE FIELD',newsTitle:'Inside PARTECH.',
  contactLabel:'LET’S CONNECT',contactTitle:'Let’s Build the Next Chapter.',contactText:'We welcome conversations with industry partners, researchers and future teammates.',contactPending:'Our partnership contact details will be shared here soon.',contactPrompt:'For partnership, research and team inquiries:',emailUs:'Write Us a Message',downloadDeck:'Download Partnership Deck',readMore:'Read More',
  story:'Our Story',team:'Team',opportunities:'Partnership Opportunities',updates:'Updates',media:'From the Field',
  disciplines:[['Mechanical Design','Bringing the prototype’s physical structure and components together.'],['Electrical Systems','Connecting the electrical elements that support the prototype.'],['Software & Control','Developing the software and control side of the engineering process.'],['System Integration','Working across disciplines to bring the prototype together.']],
  milestones:[['assets/awards.jpg','TEKNOFEST','Competition Experience','Our team and prototype at the Hyperloop competition award ceremony.'],['assets/team.jpg','TEAM','A Shared Achievement','Celebrating the effort behind our prototype with the people who made it possible.'],['assets/team-pod.jpg','PROTOTYPE','Engineering on Display','Sharing our Hyperloop prototype and our engineering journey with visitors.']],
  articles:[['assets/event.jpg','EVENT','Sharing Our Engineering','A closer look at our prototype and the conversations around it.','Events give our team a chance to explain our work, share ideas and bring engineering closer to visitors. These photographs document PARTECH’s presence at TEKNOFEST.'],['assets/pod.jpg','PROTOTYPE','A Closer Look at Our Pod','Explore the prototype displayed alongside its exposed hardware.','The display brings our pod shell and hardware into view. It offers a closer look at the physical prototype developed by our team. Detailed technical specifications will be added once confirmed.'],['assets/awards.jpg','TEAM','Moments From the Competition','A record of the people and experiences behind PARTECH.','Our competition photographs capture an important part of our team’s journey: working together, presenting our prototype and sharing the experience.']],
  paths:[['Industry & Manufacturing','Support the team through materials, components and manufacturing expertise.'],['Technology & Research','Explore opportunities for technical exchange and research collaboration.'],['Team Support','Help create the resources and opportunities for our next stage.']],
  placeholder:'Partner Logo',placeholderTitle:'Partner introduction',placeholderDescription:'Company introduction and contribution will be added here.',placeholderTypes:['Industry','Academia','Manufacturing','Research','Technology','Support'],
 },
 tr: {
  home:'Ana Sayfa',about:'Hakkımızda',technology:'Teknoloji',achievements:'Başarılar',partners:'Ortaklarımız',news:'Haberler',contact:'İletişim',
  heroLabel:'PARTECH HYPERLOOP · PROTOTİP GELİŞTİRME',heroTitle:'Ulaşımın Geleceğini Tasarlıyoruz.',heroText:'Biz PARTECH. Tasarım, uygulamalı geliştirme ve iş birliğiyle fikirlerini hayata geçiren bir Türk Hyperloop mühendislik takımıyız.',explore:'Aracımızı Keşfet',partner:'İş Birliği Yapalım',focus:'Odak noktamız',approach:'Yaklaşımımız',prototype:'Tasarım ve Prototip',strength:'Gücümüz',teamwork:'Birlikte Mühendislik',discover:'Mühendisliğimizi keşfet',
  techLabel:'PARTECH TEKNOLOJİ',techTitle:'Mühendislik Fikirlerinden Gerçek Bir Prototipe.',techIntro:'Yeni nesil ulaşım üzerine çalışmalarımızın arkasındaki prototipi ve mühendislik disiplinlerini keşfedin.',podCaption:'TEKNOFEST’te sergilenen prototipimiz.',ourApproach:'Yaklaşımımızı Keşfet',
  aboutLabel:'BİZ KİMİZ?',aboutTitle:'Birlikte Geliştiriyor, İleriye Bakıyoruz.',aboutText:'PARTECH, Hyperloop teknolojisi üzerine çalışan bir takımı bir araya getiriyor. Yolculuğumuz, mühendislik fikirlerini fiziksel bir prototip geliştirmenin kazandırdığı deneyimle buluşturuyor.',aboutText2:'Bilgi paylaşımı, sanayi desteği ve gelecekteki uluslararası iş birlikleriyle çalışmalarımızı güçlendirmeyi hedefliyoruz. Her yeni aşama; öğrenmek, geliştirmek ve birlikte üretmek için bir fırsat.',principle1:'Uygulamalı Mühendislik',principle1Text:'Prototip geliştirme ve iş birliğiyle öğreniyoruz.',principle2:'Ortak Hedefler',principle2Text:'Takımımızı sanayi ve araştırma topluluklarıyla buluşturuyoruz.',teamCaption:'Hyperloop yarışmasında PARTECH takımı.',teamNote:'Prototipin arkasındaki insanlar.',
  achievementsLabel:'YOLCULUĞUMUZDAN',achievementsTitle:'Deneyimle Gelişiyoruz.',achievementsText:'Sahadan fotoğraflarla takımımıza, prototipimize ve yarışma yolculuğumuza yakından bakın.',
  partnersLabel:'SPONSORLAR VE ORTAKLAR',partnersTitle:'Birlikte İlerliyoruz.',partnersText:'Mühendislik, iş birliğiyle gelişir. Yolculuğumuzun bir sonraki aşamasına katkıda bulunmak isteyen kurumları aramıza bekliyoruz.',becomePartner:'İş Ortağımız Olun',
  teamLabel:'PARTECH’İN ARKASINDAKİ EKİP',teamTitle:'Tek Takım. Farklı Disiplinler. Ortak Bir Yön.',teamText:'Prototipimiz, PARTECH’in arkasındaki insanların merakını, emeğini ve farklı bakış açılarını bir araya getiriyor.',join:'Takımımızla Tanışın',
  newsLabel:'SAHADAN NOTLAR',newsTitle:'PARTECH’e Yakından Bakın.',
  contactLabel:'İLETİŞİME GEÇELİM',contactTitle:'Bir Sonraki Adımı Birlikte Atalım.',contactText:'Sanayi ortakları, araştırmacılar ve gelecekteki takım arkadaşlarımızla tanışmak istiyoruz.',contactPending:'İş birliği için iletişim bilgilerimizi yakında burada paylaşacağız.',contactPrompt:'İş birliği, araştırma ve takım başvuruları için:',emailUs:'Bize Yazın',downloadDeck:'Sponsorluk Dosyasını İndir',readMore:'Devamını Oku',
  story:'Hikâyemiz',team:'Takım',opportunities:'İş Birliği Fırsatları',updates:'Güncellemeler',media:'Sahadan Notlar',
  disciplines:[['Mekanik Tasarım','Prototipin fiziksel yapısını ve bileşenlerini bir araya getiriyoruz.'],['Elektrik Sistemleri','Prototipin çalışmasını destekleyen elektrik bileşenleri üzerine çalışıyoruz.'],['Yazılım ve Kontrol','Mühendislik sürecinin yazılım ve kontrol tarafını geliştiriyoruz.'],['Sistem Entegrasyonu','Prototipi bir araya getirmek için disiplinler arasında birlikte çalışıyoruz.']],
  milestones:[['assets/awards.jpg','TEKNOFEST','Yarışma Deneyimi','Hyperloop yarışması ödül töreninde takımımız ve prototipimiz.'],['assets/team.jpg','TAKIM','Birlikte Başarıyoruz','Prototipimizin arkasındaki emeği, bu yolculuğu mümkün kılan insanlarla paylaşıyoruz.'],['assets/team-pod.jpg','PROTOTİP','Mühendisliğimizi Paylaşıyoruz','Hyperloop prototipimizi ve mühendislik yolculuğumuzu ziyaretçilerle buluşturuyoruz.']],
  articles:[['assets/event.jpg','ETKİNLİK','Mühendisliğimizi Anlatıyoruz','Prototipimize ve çevresinde gelişen paylaşımlara yakından bakın.','Etkinlikler; çalışmalarımızı anlatmak, fikir alışverişi yapmak ve ziyaretçileri mühendislikle buluşturmak için bir fırsat. Bu fotoğraflar, PARTECH’in TEKNOFEST deneyimini yansıtıyor.'],['assets/pod.jpg','PROTOTİP','Aracımıza Yakından Bakın','Gövdesi ve donanımıyla sergilenen prototipimizi keşfedin.','Sergi alanı, aracımızın gövdesini ve donanımını bir arada görme fırsatı sunuyor. Takımımızın geliştirdiği fiziksel prototipe yakından bakabilirsiniz. Ayrıntılı teknik veriler doğrulandıktan sonra eklenecek.'],['assets/awards.jpg','TAKIM','Yarışmadan Anlar','PARTECH’in arkasındaki insanları ve deneyimleri bir araya getiren kareler.','Yarışma fotoğraflarımız; birlikte çalışmayı, prototipimizi tanıtmayı ve deneyimlerimizi paylaşmayı içeren takım yolculuğumuzun önemli bir bölümünü kayda geçiriyor.']],
  paths:[['Sanayi ve Üretim','Malzeme, bileşen ve üretim uzmanlığıyla takımımıza destek olun.'],['Teknoloji ve Araştırma','Teknik bilgi paylaşımı ve araştırma iş birliği fırsatlarını keşfedin.'],['Takım Desteği','Bir sonraki aşamamız için kaynak ve fırsatların oluşmasına katkı sağlayın.']],
  placeholder:'Partner Logosu',placeholderTitle:'İş ortağı tanıtımı',placeholderDescription:'Firma tanıtımı ve PARTECH’e katkısı buraya eklenecek.',placeholderTypes:['Sanayi','Akademi','Üretim','Araştırma','Teknoloji','Destek'],
 }
};
